### ISSUE TITLE
Where are the .NDF files located?

### ISSUE THREAD

**Issue by shellwhale** [BE3dARt/WARNO-DATA#12]
I can't find the files in the game folder, where are they located?

**Comment by dreamfarer** [comment]
Hey @shellwhale! 👋🏽 The game files are located at **...\steamapps\common\WARNO\Mods\ModData\base.zip**.

**Comment by dreamfarer** [comment]
I have to say, sadly, I've neglected this repository a bit. I hope I can get back to it one day and finish the .ndf parser 😆.

**Comment by m1rza-s** [comment]
You can create your own NDFs by runinng the `CreateNewMod.bat` which is located in `[your steam lib dir]\steamapps\common\WARNO\Mods`

**Comment by dreamfarer** [comment]
Wow! Didn't know this! Thank you @m1rza-s! ❤️

**Comment by m1rza-s** [comment]
> I have to say, sadly, I've neglected this repository a bit. I hope I can get back to it one day and finish the .ndf parser 😆.

My parser already works, could gotta smack my objects into JSON if you need?

**Comment by dreamfarer** [comment]
Oh, wow, that's impressive @m1rza-s! 🚀  Are there any plans to make the parser or the parsed data available to the public? 👀 I was initially thinking of creating a web API for vehicle data queries, like for comparisons. But now, I'm unsure about my next steps, especially since I've been out of touch with the WARNO community for over a year. I'm not even sure if it's worth the effort, haha.

Thank you so much for the offer! I need to decide how to move forward with this project. I might reach out to you once I've made up my mind.

**Comment by m1rza-s** [comment]
TBH you're not missing much. Eugen seems to be determined to drive WARNO into the ground.

Also, have a look at https://www.warno-armory.com/

**Comment by shellwhale** [comment]
@m1rza-s where can we find your parser?

**Comment by m1rza-s** [comment]
> @m1rza-s where can we find your parser?

Nowhere. Its not open source.

**Comment by dreamfarer** [comment]
> TBH you're not missing much. Eugen seems to be determined to drive WARNO into the ground.
> 
> Also, have a look at https://www.warno-armory.com/

Based on your feedback, I'm thinking of converting this repository into a pure wiki. Perhaps in the future, when I have more time, I'll consider creating an NDF parser again. However, as you've pointed out, there are already many tools available. It seems that this repository is primarily used for looking up variable definitions or game mechanic descriptions.

**Comment by m1rza-s** [comment]
>  looking up variable definitions or game mechanic descriptions.

That's exactly how I used it.
