### ISSUE TITLE
Error While Trying to Extract DivisionRules.ndf

### ISSUE THREAD

**Issue by wolff69** [BE3dARt/WARNO-DATA#3]
I would like to first say that you have done a fantastic job on the project however, the data extraction keeps throwing an error with newer versions of the files used to create the export csv, I was wondering if I could get your input updating the project so it can handle the newer data fields added since the patch this was made for?

returned value is 0
Traceback (most recent call last):

    DivisionRulesArray = helper.csv.export(procedures.DivisionRules.extract("/Scripts/data/DivisionRules.ndf", "/Scripts/data/Divisions.ndf"), version, "DivisionRules", keywords.deck) 

WARNO-DATA-main\WARNO-DATA-main\Scripts\procedures\DivisionRules.py", line 107, in extract
    extractDivisionRules(open(rootDirectory + filePathDivisionRules,"r").read(), 0, Divisions, 0)

WARNO-DATA-main\WARNO-DATA-main\Scripts\procedures\DivisionRules.py", line 28, in extractDivisionRules
    extractDivisionRules(temporaryStr, level + 1, Divisions, divisionIndex)

WARNO-DATA-main\Scripts\procedures\DivisionRules.py", line 46, in extractDivisionRules
    DivisionRules[-1][listIndex] = [DivisionRules[-1][listIndex][0], Divisions[divisionIndex][listIndex][1]] 
                                                                     ~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by dreamfarer** [comment]
Welcome, @wolff69! I'm surprised to see your interest in this project despite its rather messy code, haha! I will take a quick look at it tomorrow morning. However, please note that I have university exams this week. If I can't address it tomorrow, I'll make sure to give it attention on Friday, alright? It would be fantastic to collaborate with you and bring this project back on track.

Anyhow, I believe the optimal approach would be to rewrite the entire code, especially considering that I've completed an entire semester on Python at university since then. In approximately five weeks from now, I'll be on summer vacation, and if it is desired, I can rewrite it then.

**Comment by dreamfarer** [comment]
@wolff69 I have identified the error in the code. However, there are some challenges in fixing it due to the messy state of the code. Eugen has made changes to variable names, which the program relies on to navigate through the files. As a result, the array remains empty, and nothing is extracted from _divisons.ndf_.

I'm planning to perform a quick & dirty **fix this Friday** so that you are able to at least read out the files. But eh, I will rewrite the code anyways over the coming weeks.

**Comment by wolff69** [comment]
Thank you for the quick response. I agree that there have been changes to the files that affect how the code behaves, I appreciate all your hard work on this wonderful tool, and i a very grateful that you are taking the time out to update the code base.
________________________________

**Comment by dreamfarer** [comment]
Hey again, @wolff69! I'm excited to announce that I've just committed the first iteration of the refactored code, which embraces a pure object-oriented approach (OOP) and utilizes regular expressions (RegEx). I couldn't wait for friday, haha!

Furthermore, I've created a new [issue](https://github.com/Perytron/WARNO-DATA/issues/4) to keep everyone informed about the progress of the refactor.

It's important to note that the first iteration successfully captures a sample from _WeaponDescriptor.ndf_ and outputs the findings to the console. The code is already much more readable and understandable. However, before moving on to the next .ndf files, my next step will be to maximize abstraction and improve readability.

**Comment by wolff69** [comment]
That is a great idea i am so glad you were able to update the code base, and appreciate all your hard work on this wonderful tool.

**Comment by dreamfarer** [comment]
Hey again, @wolff69! I'm really pleased with the progress of the new code base. _Ammunition.ndf_ and _WeaponDescriptor.ndf_ are being parsed correctly, although currently they only output the values to the console. 

Unfortunately, due to my upcoming university exams in two weeks, I won't be able to continue coding for the repository until after they are over. However, once they are done, I have nothing planned except for coding on this repository.
I'll definitely keep you updated on the progress of exporting to .csv.

**Comment by wolff69** [comment]
That is fantastic news, best wishes on your exams I hope you do well and pass with great marks. I look forward to working on the project in a few weeks as well, because I also will be going of summer break from the university.

Jefferson Community College
Department of Computer Science
________________________________

**Comment by dreamfarer** [comment]
Hey @wolff69! I wanted to inform you that I am closing this issue as I've decided not to proceed with the .ndf parser. This repository has transitioned into a dedicated wiki, as detailed in [this pull request](https://github.com/Perytron/WARNO-DATA/pull/13). If you're in need of a .ndf parser, you might find this [repository](https://github.com/Ulibos/ndf-parse) useful, as suggested in another issue.
